import { type NextPage } from "next";
import Head from "next/head";
import { Charismaicon } from "../components/svg/Attributes";
import { Logo } from "../components/svg/Logo";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>T20 Atribute Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
        <link href="https://fonts.googleapis.com/css2?family=Hammersmith+One&display=swap" rel="stylesheet"/>
      </Head>
      <main >
        <div className="background-pattern h-screen flex flex-col justify-center items-center gap-4">
          <Logo className="h-24 w-24" />
          <h1 className="text-white text-4xl font-bold font-display">T20 Attribute Calculator</h1>

          <div className="flex items-center ">
            
          </div>

        </div>
        <section>
          
        </section>

      </main>
    </>
  );
};

export default Home;
