import { type NextPage } from "next";
import Head from "next/head";
import { ApplicationLayout } from "../components/layout/ApplicationLayout";
import { DescriptionLayout } from "../components/layout/DescriptionLayout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>T20 Atribute Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
        <link href="https://fonts.googleapis.com/css2?family=Hammersmith+One&display=swap" rel="stylesheet"/>
      </Head>
      <main >
        <ApplicationLayout />
        <DescriptionLayout />
      </main>
    </>
  );
};

export default Home;
