import { type NextPage } from "next";
import Head from "next/head";
import { ApplicationLayout } from "../components/layout/ApplicationLayout";
import { DescriptionLayout } from "../components/layout/DescriptionLayout";
import { version as versionAtom } from '../atoms/version'
import { useAtom } from "jotai";
import { activeCharacter, characters, defaultCharacter } from "../atoms/characters";
import { useEffect } from "react";
import packageInfo from '../../package.json'

const Home: NextPage = () => {
  const [version, setVersion] = useAtom(versionAtom)
  const [, setChar] = useAtom(activeCharacter)
  const [, setChars] = useAtom(characters)

  useEffect(() => {
    if(version !== packageInfo.version) {
      setChar(defaultCharacter)
      setChars([])
      setVersion(packageInfo.version || '0.0.1')
    }
  }, [version, setChar, setChars, setVersion])



  return (
    <>
      <Head>
        <title>T20 Atribute Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
        <link href="https://fonts.googleapis.com/css2?family=Hammersmith+One&display=swap" rel="stylesheet"/>
      </Head>
      <main >
        <ApplicationLayout />
        <DescriptionLayout />
      </main>
    </>
  );
};

export default Home;
